### ISSUE TITLE
pan.baidu.com.py的文件操作报错

### ISSUE THREAD

**Issue by k19862217** [PeterDing/iScript#103]
大神你好，之前还是好用的，昨天开始对于文件的rename, move等操作都会报
!! Error at filemanager {u'info': [], u'errno': -6, u'request_id': 843209471919136178}
这个错误，貌似是bdstoken不对，不知道是什么原因。请问能帮忙调查一下么？万分感谢🙏

**Comment by PeterDing** [comment]
```shell
$ bp mv /g.py /gg.py
  ++ success.

$ bp rn /gg.py/g.py /ss.py
  ++ success.
```

这是我这里的操作结果，没法复现你的错误。。。

你把 ~/.bp.cookies 删掉，重新登录试试。

**Comment by k19862217** [comment]
还是不好用，不知道为什么。我用别的方法避开重命名操作了，非常感谢您的帮助
