### ISSUE TITLE
115 可不可以添加 HASH 输出

### ISSUE THREAD

**Issue by nuomi1** [PeterDing/iScript#107]
登录网页版 115，发现 115 直接把文件的 sha1 写进了网页源代码。

现在已经不相信这些秒传服务了，前不久上传一个文件夹，里面几个文件死活传不了，然后单独上传这几个文件到根目录，秒传……

百度网盘支持 `l -vv`，希望 115 也支持。

**Comment by PeterDing** [comment]
抱歉，`115.py` 已经很长时间不维护了，我已经不需要用到 115，维护 115 的原始动力已不再(｡ ˇ‸ˇ ｡)

如果你确实需要用到 `115.py` 没有的功能，建议自己修改。也可以发 pull，如果没有问题，我会合到 master 上。

**Comment by nuomi1** [comment]
好吧。
