### ISSUE TITLE
[pan.baidu.com.py]bp login 老出错了

### ISSUE THREAD

**Issue by jumpx1** [PeterDing/iScript#109]
Hi，您好
bp login
  username: jumpshare
  password:

  -- login
 ! Error 5: 请重新登录

**Comment by PeterDing** [comment]
先看看是不是 #90 的情况。
如果是，过几天我会把手动加 cookie 的功能加上。
如果不是，试试先把 `~/.bp.cookies` 删除后，再登录。

**Comment by talkxin** [comment]
好像并不是这个问题，似乎是百度把登录验证的流程改了，导致现在所有的开放式登录全挂了

**Comment by PeterDing** [comment]
@talkxin 嗯，我试了，确实如此。我尽快更新代码。

**Comment by jumpx1** [comment]
@PeterDing peter, 有什么方式把chrome的cookies转化成.bp.cookies，删除了~/.bp.cookies，重新通过bp login都登录不了。当时用chrome可以不需要验证码快速登入，应该是读取以前chrome的cookies。

**Comment by PeterDing** [comment]
已经支持 cookie 登录，[见](https://github.com/PeterDing/iScript#cookie-登录)
--------
现在用 username 和 password 登录还没好，先用 cookie 登录吧

**Comment by jumpx1** [comment]
Good, 可以了哈

**Comment by PeterDing** [comment]
@jumpx1 有多短。我这过了快6小时了，还没失效。

**Comment by jumpx1** [comment]
另外，通过save_share接口
    infos = self._get_share_infos(url, remotepath, infos)
  File "baidu.py", line xxxx, in _get_share_infos
    self.shareid = info['shareid']
KeyError: 'shareid'
没有shareid还是不能工作阿

**Comment by PeterDing** [comment]
@jumpx1 这个问题单开一个issue吧

**Comment by wangx2** [comment]
大哥们，能不能私聊

2017年3月11日 17:44，"jumpx1" <notifications@github.com>写道：

**Comment by jumpx1** [comment]
@PeterDing 登录时间是这样的，假如通过bp login cookie登录后，你退出chrome的登录窗口，此时通过bp rm test测试命令时，就不能删除了。

**Comment by loveyanbei** [comment]
jumpx1 <notifications@github.com>于2017年3月11日 周六下午5:47写道：

**Comment by loveyanbei** [comment]
Liu Yiteng <belica.ly42@gmail.com>于2017年3月11日 周六下午5:47写道：

**Comment by PeterDing** [comment]
@jumpx1 的确如此。

但是在隐身窗口登录，不要退出百度，只关闭窗口，这种情况就不会出现了。

**Comment by talkxin** [comment]
这是个好招！赞！
