### ISSUE TITLE
pan.baidu.com.py Cookie login

### ISSUE THREAD

**Issue by jacobxy** [PeterDing/iScript#114]
pan.baidu.com.py Cookie 登陆仍然需要输入中文验证码

**Comment by PeterDing** [comment]
你试试下载最新的 [pan.baidu.com.py](https://raw.githubusercontent.com/PeterDing/iScript/master/pan.baidu.com.py) 用

**Comment by jacobxy** [comment]
调用了git pull 已经获得了最新版，现在登陆报错是 ! Error 7: unknow, please feedback to author

**Comment by jacobxy** [comment]
怎么把cookie内容复制出来呀
![image](https://cloud.githubusercontent.com/assets/5415262/25602587/b826e308-2f27-11e7-9df8-34768076b647.png)

**Comment by jacobxy** [comment]
这个cookie的复制需要怎么去做！
![image](https://cloud.githubusercontent.com/assets/5415262/25602625/0489114e-2f28-11e7-8d76-90e567243b8b.png)

**Comment by PeterDing** [comment]
详见： https://github.com/PeterDing/iScript#cookie-登录

用下图中的 Cookie

<img width="133" alt="screen shot 2017-05-02 at 11 31 43" src="https://cloud.githubusercontent.com/assets/670690/25603034/1e4ff3ba-2f2b-11e7-9a18-d5dc1b9029f2.png">

**Comment by jacobxy** [comment]
多谢了，登陆成功！   ^_^
