### ISSUE TITLE
蝦米精選輯的隨機播放

### ISSUE THREAD

**Issue by Harry1993** [PeterDing/iScript#122]
Hi,

我想實現蝦米精選輯（現在跟網易學叫「歌單」了...）內的隨機播放

我嘗試著在 play() 函數中在 for loop 之前加入：

```
if args.play == 3:
            random.shuffle(songs);
```

可以實現專輯內的隨機播放（但這恰恰是我不需要的...）。

如果是精選輯的話，len(songs) = 1，shuffle 了也沒用...

請問我可以在哪裡 shuffle 精選輯的歌曲list呢？

謝謝！

Yanmao

**Comment by PeterDing** [comment]
@Harry1993 
 你可以在[这行](https://github.com/PeterDing/iScript/blob/f0255055c7194d783a189bb132d9b023fc22039d/xiami.py#L688)下面加 `random.shuffle(song_ids)`
