### ISSUE TITLE
Long playlist in Xiami

### ISSUE THREAD

**Issue by Harry1993** [PeterDing/iScript#127]
Hi Peter,

I regularly use your xiami.py. I appreciate your work!

Sometimes I play a really long playlist with 150 songs for example, xiami.py is going to play only 50 of it. I think the reason might be that in the website, we have to click "show more songs" in order to let it show the extended list of those extra songs.

I think there is a way that we can automatically click the "show more songs" button before fetching the playlist of a long playlist. Do you have any hint about this implementation?

Thank you,

Yanmao

**Comment by PeterDing** [comment]
@Harry1993 Can you show me that xiami's url

**Comment by Harry1993** [comment]
Yes, sure.

http://www.xiami.com/collect/41978875?spm=a1z1s.6929277.1561534893.7.L0tISC

**Comment by PeterDing** [comment]
@Harry1993 it is ok, try again.

**Comment by Harry1993** [comment]
It works! Awesome!

Thank you so much,

Yanmao
