### ISSUE TITLE
请问有意向把pan.baidu.com.py扩展成FUSE吗？

### ISSUE THREAD

**Issue by mo-han** [PeterDing/iScript#129]
我不太在行，光是现有的代码还没读完，要是您愿意的话应该会很快？（被拖走……）

**Comment by PeterDing** [comment]
@mo-han 不懂 FUSE 是什么。。。

**Comment by mo-han** [comment]
用户空间文件系统，可以在系统中挂载为一个虚拟文件系统。

**Comment by PeterDing** [comment]
@mo-han 这个不会，没搞过。并且我觉得没必要，Google, Dropbox 都有现成都工具。
