### ISSUE TITLE
能不能支持百度网盘的 Hash 比对？

### ISSUE THREAD

**Issue by nuomi1** [PeterDing/iScript#13]
最近备份些文件，都是秒传的。
有些过了 4GB，想去转存却没人共享出来。
支持 Hash 对比就不用浪费那么多流量和时间去备份了。
其实是不想开 VIP（死

**Comment by PeterDing** [comment]
@nuomi1 我不太明白你的意思.
"有些过了 4GB，想去转存却没人共享出来。" 是指你的硬盘上已经有了这个文件,但不想上传,想转存别人共享的. ?
hash 对比是什么意思,你想的大致过程是什么? vip 提供这个功能吗?

**Comment by nuomi1** [comment]
用客户端备份，文件超过 4GB 无法直接上传。想到之前的几个文件都可以秒传，想转存别人上传的文件。Google 了结果没人分享出来。
现在想用别的「黑科技」绕过官方客户端上传（秒传）超过 4GB 的文件。

iScript 可以秒传吗？

**Comment by PeterDing** [comment]
@nuomi1 
秒传的前提是百度的服务器上已经有了要上传的文件,
不管你要上传的文件是否大于4G,如果该文件不存在于
百度上,那么秒传会失败,只能正常上传.

iScript对任何上传的文件首先秒传,如果秒传失败,则进行正常上传.
