### ISSUE TITLE
Xiami cookies

### ISSUE THREAD

**Issue by Harry1993** [PeterDing/iScript#135]
Hello Peter,

Due to Taobao's anti-crawling mechanism, cookies need updated every time `xiami.py` gets caught (i.e., 「亲,访问受限了」). Is there any way to bypass it?

Thanks,

Yanmao

**Comment by Harry1993** [comment]
Also, at

https://github.com/PeterDing/iScript/blob/bfa5099403ab86fa8e8a8a00f9145a0cbce02816/xiami.py#L713

we pass over `params=params` to function `_request()`, hence at

https://github.com/PeterDing/iScript/blob/bfa5099403ab86fa8e8a8a00f9145a0cbce02816/xiami.py#L162

we should add `params=None` as another parameter. Also add `params=params` to

https://github.com/PeterDing/iScript/blob/bfa5099403ab86fa8e8a8a00f9145a0cbce02816/xiami.py#L166

Thanks!

**Comment by PeterDing** [comment]
@Harry1993 Thank you for debugging.
Recently, I have not idea how to handle Taobao's new cookie policy. I need time to hack it.
And the `_request` code error will be fixed as far as possible.
