### ISSUE TITLE
115网盘用不了了么？

### ISSUE THREAD

**Issue by leviBar** [PeterDing/iScript#139]
百度网盘离线下载超过10个就要输入验证码，而且这个验证码很难识别。
刚注册了个115会员，才发现，115脚本用不了。哭哈。楼主可以继续更新115么？

**Comment by PeterDing** [comment]
@leviBar 115的脚步已经不再维护了

百度网盘离线多次是要输验证码的，这个是百度网盘设定的，没法解决，只能手输了。

**Comment by leviBar** [comment]
@PeterDing 非常感谢楼主的回复。我在找找可以下载磁力链和电驴的其他工具吧。
