### ISSUE TITLE
百度盘工具utime失败的问题

### ISSUE THREAD

**Issue by fhmob** [PeterDing/iScript#14]
hi，
非常感谢您提供的工具，我在树莓派和一块硬盘上下载一些移动APP开发的教学视频，对我的帮助很大。

不过我在使用中有个问题，刚开始以为是断点续传的事情。

——————————————————————————————————————
已发出 HTTP 请求，正在等待回应... 200 OK
长度：2015080583 (1.9G) [application/zip]
正在保存至: “/home/pi/disk/50g/download/Java4Android.zip.tmp”

19% [======>                              ] 396,294,189 --.-K/s 用时 60m 1s  s

2015-01-06 01:00:18 (107 KB/s) - 在 396294189/2015080583 字节处发生读取错误 ( 连接超时)。重试中。

--2015-01-06 01:00:19--  (尝试次数： 2)  http://nj.baidupcs.com/file/5ce62364db524cab6650b887509ef013……&vbdid=-&fin=Java4Android.zip
正在连接 nj.baidupcs.com (nj.baidupcs.com)|58.217.200.14|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 206 Partial Content
长度：2015080583 (1.9G)，剩余 1618786394 (1.5G) [application/zip]
正在保存至: “/home/pi/disk/50g/download/Java4Android.zip.tmp”

90% [++++++========================>    ] 1,815,871,488  391K/s 用时 2h 46m

2015-01-06 03:47:05 (139 KB/s) - 在 1815871488 字节处连接关闭。重试中。

--2015-01-06 03:47:07--  (尝试次数： 3)  http://nj.baidupcs.com/file/5ce62364db524cab66……Android.zip
正在连接 nj.baidupcs.com (nj.baidupcs.com)|58.217.200.14|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 206 Partial Content
长度：2015080583 (1.9G)，剩余 199209095 (190M) [application/zip]
正在保存至: “/home/pi/disk/50g/download/Java4Android.zip.tmp”

100%[+++++++++++++++++++++++++++++++===>] 2,015,080,583  470K/s 用时 7m 12s

utime(/home/pi/disk/50g/download/Java4Android.zip.tmp): 不允许的操作
2015-01-06 03:54:21 (450 KB/s) - 已保存 “/home/pi/disk/50g/download/Java4Android.zip.tmp” [2015080583/2015080583])

——————————————————————————————————————
我默认使用wget下载，下载了一部分，应该是断开了，重新连接之后，再次写入就出现了错误，导致前面下载的1.7G左右的内容前功尽弃。

我看了手册，里面可以使用aria2引擎，里面有分片的参数。

问题：
1、是不是只要用aria引擎就默认可以断点续传了？
2、aria2的命令中带参数c可以断点，这个脚本怎么使用？

谢
——————————————————

我想问题是最后的“utime(/home/pi/disk/50g/download/Java4Android.zip.tmp): 不允许的操作”，我下载其他的文件OK，这个是？

**Comment by PeterDing** [comment]
@fhmob 我想你碰到的问题应该是由百度网盘服务器出错产生的。
用百度网盘脚本下载时，不论你是用wget还是aria2，都是默认开启断点续传的。

如果你的下载中断，不论是人为的还是服务器出错产生的，你可以再次运行命令，下载工具会自动开启断点续传。
人为的出错（如Ctrl-C）完全不会影响断点续传，而服务器出错可能会让断点续传不能运行，但是这种情况也是极少数的，目前为止我遇到过的不超过10次，可忽略。

但是，如果你用脚本进行的任何下载都遇到你上面提到的情况，请告诉我。

-----------
P.S.
用aria2下载可用参数 -a 10，数字是你要用的分段数，最大是16。

**Comment by fhmob** [comment]
感谢，这个只是其中一个任务，我使用screen，同时下载了五个任务，仅此一例错误，我看提示应该是下载完了，是不是最后一步出差错了。utime这个，我当前这个文件的大小是0字节。
