### ISSUE TITLE
你好，转存好像不行了。

### ISSUE THREAD

**Issue by leviBar** [PeterDing/iScript#141]
楼主，你好。之前都是用 python pan.baidu.com.py save "https://pan.baidu.com/s/1cpVD9c" /path/ -s "i0xc"  将别人分享的地址保存 到 自己网盘。
但今天提示：
 ++ transfer: /sharelink1154348095-647178598575518/gzgg2
  !! Error at save_share, errno: {u'errno': -3, u'request_id': 479152203611622481}
^C  !! Signal: 2
换了不同账号，不同地址也都一样的错，请问楼主知道什么原因么？非常感谢楼主。

**Comment by PeterDing** [comment]
@leviBar 百度api更新，刚才更新了代码，下载最新的 `pan.baidu.com.py` 试试。

**Comment by leviBar** [comment]
哇。楼主太棒了。爱你。么么哒
