### ISSUE TITLE
请问现在脚本还能通过dlink链接下载文件吗？

### ISSUE THREAD

**Issue by Waha-Liu88** [PeterDing/iScript#143]
百度网盘dlink下载问题

**Comment by PeterDing** [comment]
@Will-Liu88 `dlink` 是什么样的，发个来看看

**Comment by Will-Liu88** [comment]
https://d.pcs.baidu.com/file/461548d33eaf0ff9b572da96461c254a?fid=4225848242-250528-818305021191962&rt=pr&sign=FDtAERVCY-DCb740ccc5511e5e8fedcff06b081203-vScl%2FBA7RqowlN%2BjqiMSd3zetzA%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=1957558929609295626&dp-callid=0&dstime=1553564475&r=809089518&vip=0  
这是浏览器端点下载文件时产生的dlink 文件下载链接，以前能下载 现在貌似不能了。@PeterDing

**Comment by Will-Liu88** [comment]
> @Will-Liu88 `dlink` 是什么样的，发个来看看

现在是如何还能下载文件么？

**Comment by PeterDing** [comment]
@Will-Liu88 这个链接以前也不能下的。

但是这种直接从浏览器获得的链接是可以直接用下载工具下载的，不需要交给 pan.baidu.com.py 下载。

用任何一个下载工具下载都行，如果你想分段加速下载，可以试试 [aget](https://github.com/PeterDing/aget) 或者 [aget-rs](https://github.com/PeterDing/aget-rs)。

**Comment by Will-Liu88** [comment]
> @Will-Liu88 这个链接以前也不能下的。
> 
> 但是这种直接从浏览器获得的链接是可以直接用下载工具下载的，不需要交给 pan.baidu.com.py 下载。
> 
> 用任何一个下载工具下载都行，如果你想分段加速下载，可以试试 [aget](https://github.com/PeterDing/aget) 或者 [aget-rs](https://github.com/PeterDing/aget-rs)。

这种也不能用下载工具下吧，你的脚本 是如何获取到下载链接的我看了下也是dlink 不是从浏览器获取到的？

**Comment by PeterDing** [comment]
@Will-Liu88 百度网盘有获取文件的api，使用时要带上cookies，发起请求后就会跳转到你上面的链接。
跳转后的链接不需要带cookies，所以可以用下载工具下载。

https://github.com/PeterDing/iScript/blob/90b786dfe2eab3d7316536ba0357b7c13ac2a3f5/pan.baidu.com.py#L761

**Comment by Will-Liu88** [comment]
> @Will-Liu88 百度网盘有获取文件的api，使用时要带上cookies，发起请求后就会跳转到你上面的链接。
> 跳转后的链接不需要带cookies，所以可以用下载工具下载。
> 
> [iScript/pan.baidu.com.py](https://github.com/PeterDing/iScript/blob/90b786dfe2eab3d7316536ba0357b7c13ac2a3f5/pan.baidu.com.py#L761)
> 
> Line 761 in [90b786d](/PeterDing/iScript/commit/90b786dfe2eab3d7316536ba0357b7c13ac2a3f5)
> 
>  dlink = ('http://d.pcs.baidu.com/rest/2.0/pcs/file?method=downlo

**Comment by Will-Liu88** [comment]
获取文件api请求下载不稳定，部分rar,大文件不能下载，这 是服务器问题？

**Comment by Will-Liu88** [comment]
> @Will-Liu88 百度网盘有获取文件的api，使用时要带上cookies，发起请求后就会跳转到你上面的链接。
> 跳转后的链接不需要带cookies，所以可以用下载工具下载。
> 
> [iScript/pan.baidu.com.py](https://github.com/PeterDing/iScript/blob/90b786dfe2eab3d7316536ba0357b7c13ac2a3f5/pan.baidu.com.py#L761)
> 
> Line 761 in [90b786d](/PeterDing/iScript/commit/90b786dfe2eab3d7316536ba0357b7c13ac2a3f5)
> 
>  dlink = ('http://d.pcs.baidu.com/rest/2.0/pcs/file?method=download'

获取文件api请求下载不稳定，部分rar,大文件不能下载，这 是服务器问题？

**Comment by PeterDing** [comment]
> > @Will-Liu88 百度网盘有获取文件的api，使用时要带上cookies，发起请求后就会跳转到你上面的链接。
> > 跳转后的链接不需要带cookies，所以可以用下载工具下载。
> > [iScript/pan.baidu.com.py](https://github.com/PeterDing/iScript/blob/90b786dfe2eab3d7316536ba0357b7c13ac2a3f5/pan.baidu.com.py#L761)
> > Line 761 in [90b786d](/PeterDing/iScript/commit/90b786dfe2eab3d7316536ba0357b7c13ac2a3f5)
> > dlink = ('http://d.pcs.baidu.com/rest/2.0/pcs/file?method=download'
> 
> 获取文件api请求下载不稳定，部分rar,大文件不能下载，这 是服务器问题？

这是另外的问题，你可以重新开一个 issue.
