### ISSUE TITLE
get_share_list 接口访问出错了

### ISSUE THREAD

**Issue by jumpx1** [PeterDing/iScript#151]
Hi Peter

目前get_share_list接口访问出错：
 {u'errno': -19, u'show_msg': u'\u8bbf\u95ee\u9891\u7387\u592a\u5feb\u5566\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5', u'request_id': 8968832465118416526}
  !! Error at _get_share_list

看了下，好像百度接口又有变化：

uk | 2574033100
-- | --
shareid | 3253827698
order | other
desc | 1
showempty | 0
web | 1
page | 1
num | 100
dir | /sharelink2574033100-11535532155456/123
t | 0.8552544112110815
channel | chunlei
web | 1
app_id | 250528
bdstoken | null
logid | MTU4NTQ0ODM0NjI2NTAuMzQwMDQwODc2ODEzNzg2MTQ=
clienttype | 0

多了一个logid，是不是又得改接口了？

**Comment by PeterDing** [comment]
@jumpx1 感谢反馈

应该是你访问太快的问题。
```
{'errno': -19, 'show_msg': '访问频率太快啦，请稍后再试', 'request_id': 8968832465118416526}
```

**Comment by jumpx1** [comment]
调用接口啊，怎么修改啊，加了延时也不行。

**Comment by jumpx1** [comment]
比如测试接口：   加上两行代码，_get_share_list就会报这种错误。
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     while infos:
            info = infos.pop(0)
            while True:
                print s % (1, 97, '  ++ transfer:'), info['path']
                
                **xinfo=self._get_share_list(info)
                print  'xxxxxxxxxxxxxxxx', xinfo**
  
                result = self._share_transfer(url, info)
                if result['errno'] == 0:

**Comment by jumpx1** [comment]
之前没有出现这种问题。

**Comment by jumpx1** [comment]
@PeterDing 麻烦看看，谢谢。

**Comment by PeterDing** [comment]
@jumpx1 `'errno': -19`错误与代码无关，应为你频繁的调用这个api，baidu的服务器禁止了你的请求。可能在未来的24小时内，你如果没有调用这个接口，就会解封吧。具体时间我也不清楚。

**Comment by jumpx1** [comment]
@PeterDing 谢谢，还真是调试的问题。今天试了下，可以。
