### ISSUE TITLE
Ubuntu14.04百度网盘无法登陆ConnectionError: ('Connection aborted.', ResponseNotReady())

### ISSUE THREAD

**Issue by GerrieWell** [PeterDing/iScript#31]
commit  99519d4c790014a8a9023d85c79b7e509ce51b41
log:

/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "pan.baidu.com.py", line 3151, in <module>
    main(argv)
  File "pan.baidu.com.py", line 2738, in main
    x.login(username, password)
  File "pan.baidu.com.py", line 290, in login
    r = ss.post(url, data=data)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 425, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='passport.baidu.com', port=443): Max retries exceeded with url: /v2/api/?login (Caused by ProtocolError('Connection aborted.', ResponseNotReady()))

按照#18 按照了所有依赖.似乎不是依赖问题?

    pip2 install --upgrade requests
    pip2 install --upgrade requests-toolbelt
    pip2 install rsa
    pip2 install pyasn1

Ubuntu14.04 64bit python2.7 
我记得安装urllib3后有些.py运行不了.我自己到 /usr/...改了几个文件的import .. 应该不关事吧...

**Comment by PeterDing** [comment]
是requests的问题，见：  
https://github.com/kennethreitz/requests/issues/2568  
https://github.com/kennethreitz/requests/search?q=ResponseNotReady&type=Issues&utf8=%E2%9C%93  

用2.6.0就好。
```
pip2 install requests==2.6.0
```

**Comment by PeterDing** [comment]
requests 已发 2.7.0，这个bug已修复。
