### ISSUE TITLE
AttributeError: 'module' object has no attribute 'packages'

### ISSUE THREAD

**Issue by asuna** [PeterDing/iScript#34]
>root:iScript# python pan.baidu.com.py 

错误详情：
>Traceback (most recent call last):
>  File "pan.baidu.com.py", line 7, in <module>
>    requests.packages.urllib3.disable_warnings() # disable urllib3's warnings >https://urllib3.readthedocs.org/en/latest/security.html#insecurerequestwarning
>AttributeError: 'module' object has no attribute 'packages'

搜索一番没能自己解决，只能麻烦了

**Comment by PeterDing** [comment]
https://github.com/PeterDing/iScript/wiki/%E6%89%8B%E5%8A%A8%E8%A7%A3%E5%86%B3pan.baidu.com.py%E4%BE%9D%E8%B5%96%E5%8C%85

**Comment by asuna** [comment]
解决了，thx
