### ISSUE TITLE
登录提示成功，然而之后操作却提示失败

### ISSUE THREAD

**Issue by with0out** [PeterDing/iScript#36]
$ bp g
  username: 
  password:
-- login
 ! Error 257: 需要验证码
  ++ 验证码已保存至
  输入验证码:
  ++ login succeeds.

$ bp ls
  -- check_login fail

  !! cookie is invalid, please login

**Comment by PeterDing** [comment]
你把 ```~/.bp.cookies``` 删了, 再登录试试。

**Comment by with0out** [comment]
好了...真奇怪...
谢谢~
