### ISSUE TITLE
百度盘添加磁链出错

### ISSUE THREAD

**Issue by zanderzhng** [PeterDing/iScript#42]
提示!! Error at _get_magnet_info: magnet cannot parse
对应的种子没有问题。

**Comment by PeterDing** [comment]
百度只能分析其爬到的有torrent的magnet，和用户上传的torrent转换成的magnet，如果者两者都没有则返回你遇到的错误。
解决方法是上传你的torrent到百度，再通过这个torrent的magnet下载。
工具你可以用 bt.py

**Comment by zanderzhng** [comment]
明白了，多谢。
