### ISSUE TITLE
pan.baidu.com 下载报错:  EXIT STATUS ==> 2048

### ISSUE THREAD

**Issue by imfangs** [PeterDing/iScript#88]
下载一个文件夹,  进度到  2030 / 4649 时报错 : 

./pan.baidu.com.py d https://pan.baidu.com/disk/home\#list/path\=%2F%E8%BF%8E%E6%94%BF%E5%A4%A7%E5%9B%BE\(1\) -R

  ++ download: # 2030 / 4649 # BU7A1607.JPG
--2016-10-13 10:39:50--  http://c.pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=/%E8%BF%8E%E6%94%BF%E5%A4%A7%E5%9B%BE%281%29/BU7A1607.JPG
Resolving c.pcs.baidu.com... 36.110.198.12
Connecting to c.pcs.baidu.com|36.110.198.12|:80... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2016-10-13 10:39:50 ERROR 503: Service Temporarily Unavailable.

 ---###   EXIT STATUS ==> 2048   ###---

  ===>  wget -c -O "/Volumes/Fangs/iScript/迎政大图(1)/BU7A1607.JPG.tmp" --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" --header "Referer:http://pan.baidu.com/disk/home" --header "Cookie: HOSUPPORT=1; BD_LAST_QID=$$$; BDSVRTM=0; BDUSS=$$$; USERNAMETYPE=1; PANWEB=1; SAVEUSERID=$$$; BAIDUID=$$$:FG=1; __bsi=$$$; SCRC=$$$; PSTM=1476256094; BIDUPSID=$$$; PANPSC=; PTOKEN=$$$; HISTORY=$$$; STOKEN=$$$; UBI=$$$; H_PS_PSSID=$$$; BD_HOME=0" "http://c.pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=/%E8%BF%8E%E6%94%BF%E5%A4%A7%E5%9B%BE%281%29/BU7A1607.JPG"

单独使用 wget 命令, 报了 503 错误
Resolving c.pcs.baidu.com... 36.110.198.12
Connecting to c.pcs.baidu.com|36.110.198.12|:80... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2016-10-13 10:48:25 ERROR 503: Service Temporarily Unavailable.

**Comment by PeterDing** [comment]
服务器出场，试试：

```
./pan.baidu.com.py d https://pan.baidu.com/disk/home\#list/path\=%2F%E8%BF%8E%E6%94%BF%E5%A4%A7%E5%9B%BE\(1\) -R -tfs
```

**Comment by sqjs** [comment]
加了 -tfs 还是报同样的错误.
下载其他目录没有问题, 不知道是什么原因..
